import {  Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const inter =   Inter({subsets:["latin"]});
export const metadata = {
  title: "AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme:dark,
    }}>

    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className} `}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/*Header*/}
            <Header/>
            <main className="min-h-screen">{children}</main>
            {/*Footer*/}
            <footer className="bg-gray-800 py-2">
              <div className="container mx-auto px-4 text-center text-muted-foreground">
                <p>
                  Created By Adarsh Kasliwal 
                </p>
              </div>
            </footer>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
